data-tables/data-tables/nft.trading.md
=> add looksrare to supported NFT list

bounties/wizard-request-program.md, dune-engine-v2-beta/dunes-new-query-engine/community-data/flashbots.md
The old links were not working.
=> Fix discord links for Dune and Flashbots

dune-engine-v2-beta/dunes-new-query-engine/query-engine.md
=> some typo fixes

data-tables/abstractions/dex.trades.md, data-tables/abstractions/erc-20-balances.md, data-tables/abstractions/labels.md, data-tables/abstractions/nft.trading.md, data-tables/abstractions/special-tables/erc1155.md, data-tables/abstractions/special-tables/erc20.md, data-tables/abstractions/special-tables/erc721.md
=> fixing table headers

docs/api/.pages, docs/api/FAQ/other.md, docs/api/api-reference/.pages, docs/api/api-reference/errors.md, docs/api/eth-ber.md, docs/api/index.md, docs/api/quick-start/.pages, docs/api/quick-start/api-js.md, docs/api/quick-start/api-py.md, docs/api/quick-start/community-clients.md
Error Codes, Community Clients, and ETHBerlin Hackers guide
=> ETHBerlin API Updates

docs/api/quick-start/api-py.md
The CoW protocol Dune Client (for the API) is the best python client there is.
We should recommend it and leverage this community connection.
I also recommend contributing directly to it.
=> Reference python dune-client from Cow-Protocol

docs/spellbook/getting-started/index.md
The spellbook link was broken, updated to point to the correct url.
=> Fix broken link

docs/features/dune-v2/index.md, docs/features/dune-v2/query-engine.md, docs/getting-started/.pages, docs/getting-started/helpful-dashboards.md, docs/getting-started/index.md, docs/resources/events.md
Implemented Helpful Dashboards v1
=> Implemented Helpful Dashboards v1

docs/resources/spellbook-workshop-prerequisite.md
@cryptofreedman Could you help review and merge? Ty!
=> add spellbook prereq

docs/index.md
remove the redundant word "questions"
=> remove the redundant word "questions"

docs/javascript/mathjax.js, mkdocs.yml
See
- https://squidfunk.github.io/mkdocs-material/reference/mathjax/
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
=> Setup mathjax for equations + disable "instant loading"

zh/tables/index.md
Add tables/index.md Chinese translation
添加了tables/index.md的中文翻译（不是特别专业，欢迎指正修改）
Here is a page preview:
=> Add tables/index.md Chinese translation

docs/api/index.md
=> 第一版翻译 API板块的 index.md 文档

docs/api/index.md, docs/api/quick-start/api-py.md
=> 恢复被错误翻译的文档

docs/zh/api/index.md
=> 新版 API index.md 翻译

docs/spellbook/index.md, docs/zh/spellbook/index.md
Translate spellbook/index.md
翻译了Spellbook/index.md
这一页信息量有点大。
谢谢大家审核及修改。
=> Translate spellbook/index.md

docs/zh/spellbook/getting-started/data-sources.md
=> Translate spellbook/data-sources

docs/zh/spellbook/getting-started/spells.md, docs/zh/spellbook/getting-started/submissions.md
=> Translate spellbook/spells and spellbook/submission

docs/zh/resources/events.md, docs/zh/resources/faq/does-dune-have-a-token.md, docs/zh/resources/faq/does-dune-have-an-api.md, docs/zh/resources/faq/how-are-results-refreshing.md, docs/zh/resources/faq/how-does-dune-get-its-data.md, docs/zh/resources/press-kit.md, docs/zh/resources/spellbook-workshop-prerequisite.md, docs/zh/resources/support-feedback.md, docs/zh/resources/wizard-request-program.md, docs/zh/resources/wizard-tools.md
1. wizard-request-program.md
“The data flow” 直译为数据流，但是并未理解这块的语义。
英文原文中有提到 discord 中的 “reelancer-listing” 频道，但是我自己并未找到。
2. how-are-results-refreshing.md
“Note that the query execution queue is separate from each individual user's queue when they create and run queries in the query editor.” 这里关于 Dune 中的队列机制理解不深，翻译的中文准确性有待考证。
3. 本地 mkdocs 环境有问题，当前以 vs code 中的 markdown 预览效果为准。
=> 翻译 resources 目录

docs/zh/spellbook/getting-started/tests.md
=> Translate spellbook/tests

docs/api/quick-start/.pages, docs/api/quick-start/api-ready-queries.md, docs/api/quick-start/index.md
made four API ready queries and documentation around it. 
The index.md page cards grid seems to breakdown, and some of the text in tables wraps around no matter how many `-----` I put in the header line. Alex will need your help there :)
=> api queries

docs/api/quick-start/community-clients.md, docs/reference/.pages, docs/reference/v1-sunsetting.md
=> added sunsetting info, updated API

docs/api/FAQ/billing-pricing.md
App plans launched and we'll have a new pricing page so some of these I removed.
=> Update pricing page faq

docs/getting-started/guides/dune-guides.md
=> fix typo for two words

docs/reference/dune-v2/query-engine.md
Removing since we don't have a discord channel for it in place.
=> Removing discord channel mention for now

docs/api/index.md, docs/api/quick-start/api-use-cases.md
I changed the index page on the API. To include more information on the new page I have added specifically for use cases. As usual, I will trust you to find the right organization for this new page to fit into.
=> API Use Cases

docs/reference/dune-v2/query-engine.md
Fix some syntax display issues for the keywords samples.
=> Fix syntax for keywords sample

docs/api/quick-start/community-clients.md
I was one of the first peeps to try out the API on the private beta and decided to build the Ruby SDK for it :-)
This library currently has +350 downloads ⭐
=> Add Ruby client to the community client list

docs/reference/dune-v2/query-engine.md
Incorporating [this comment](https://discord.com/channels/757637422384283659/1051871389432422491/1052945938550902845) from Discord to our docs
=> Add more compatibility instructions for DuneSQL

docs/reference/tables/raw/bitcoin/blocks.md, docs/reference/tables/raw/bitcoin/index.md, docs/reference/tables/raw/bitcoin/outputs.md, docs/reference/tables/raw/bitcoin/transactions.md
Don't merge this until (just before) launch!
=> T-22842 Add Bitcoin table schemas

docs/api/index.md
Can someone check i added this link correctly and then merge it?
=> Add link to pricing page

docs/api/quick-start/index.md, docs/reference/dune-v2/query-engine.md
improved descriptions around breaking bytearray changes
added API example for data ingestion using python and celery workers.
=> better docs

docs/api/FAQ/functionality.md
From reading the doc it seems we are talking about V1. Please merge if this is the case.
=> Small typo

docs/reference/v1-sunsetting.md
Cleaning up the page to be more easily understandable
=> Rework sunsetting page

docs/tables/raw/index.md
=> Correction

docs/reference/dune-v2/query-engine.md
Follow up of https://dune.height.app/T-24040. 
Let's not merge this until the support is merged and rolled out (https://github.com/duneanalytics/arrakis-jobs/pull/1723 + a few more). I'll take care of this.
=> Include varbinary support for byte arrays

docs/reference/dune-v2/query-engine.md
Updates to warning labels and bytearray table format
=> Update warning labels and bytearray tables

docs/tables/decoded/index.md
Closes https://dune.height.app/T-9842
=> Adds documentation for contract batch submission

docs/reference/dune-v2/dunesql-changes.md
Documenting changes to from_hex. This should not be merged until we update trino with the from_hex changes (I can take care of it).
=> T-25892 - from_hex changes docs

docs/query/DuneSQL-reference/datatypes.md
Have confirmed links work now, so will merge this.
=> Fix two broken links in datatypes reference

docs/app/decoding-contracts.md
From time to time, we get questions regarding how long it takes to
process a contract. This will clarify.
=> T-27819: Communicate contract submission processing times more clearly

docs/resources/support-feedback.md
explain the confusing part of how upgrade plan is currently charged
=> add faq for billing

docs/app/dashboards.md, docs/app/query-editor/query-scheduler.md, docs/data-tables/bring-your-own-data.md, docs/query/.pages, docs/query/query-executions.md, docs/query/writing-efficient-queries.md
Adding a query execution page that adds condition for query execution triggers and query engine sizes.
=> Add query executions page

docs/query/DuneSQL-reference/Functions-and-operators/chain-utility-functions.md, docs/query/DuneSQL-reference/Functions-and-operators/index.md
These will be available on DuneSQL early next week.
Not sure if we should add more details - in case it's relevant, [here](https://dev.dune.com/bln/spellbook-utility-functions) is a sample dashboard on dev using them.
=> T-20627 - Document chain utility functions on DuneSQL

docs/query/DuneSQL-reference/Functions-and-operators/varbinary.md
updating the varbinary functions doc page with examples
=> Varbinary functions (DuneSQL) page update

docs/data-tables/community/index.md, docs/data-tables/community/neynar/farcaster/casts.md, docs/data-tables/community/neynar/farcaster/fids.md, docs/data-tables/community/neynar/farcaster/fnames.md, docs/data-tables/community/neynar/farcaster/index.md, docs/data-tables/community/neynar/farcaster/links.md, docs/data-tables/community/neynar/farcaster/reactions.md, docs/data-tables/community/neynar/farcaster/signers.md, docs/data-tables/community/neynar/farcaster/storage.md, docs/data-tables/community/neynar/farcaster/user_data.md, docs/data-tables/community/neynar/farcaster/verifications.md, docs/data-tables/index.md
- Added Neynar
- Fixed Reservoir formatting issue
=> feat: Add documentation for the farcaster tables powered by Neynar

docs/data-tables/community/index.md, docs/data-tables/community/neynar/farcaster/casts.md, docs/data-tables/community/neynar/farcaster/fids.md, docs/data-tables/community/neynar/farcaster/fnames.md, docs/data-tables/community/neynar/farcaster/index.md, docs/data-tables/community/neynar/farcaster/links.md, docs/data-tables/community/neynar/farcaster/reactions.md, docs/data-tables/community/neynar/farcaster/signers.md, docs/data-tables/community/neynar/farcaster/storage.md, docs/data-tables/community/neynar/farcaster/user_data.md, docs/data-tables/community/neynar/farcaster/verifications.md
- Fixes a link inside the grid card
- Fixes grid cards on the Farcaster page
- Fixes the contact text
=> fix: link to farcaster, telegram text, card rendering

docs/.pages, docs/api/api-reference/edit-queries/archive-query.md, docs/api/api-reference/edit-queries/create-query.md, docs/api/api-reference/edit-queries/get-query.md, docs/api/api-reference/edit-queries/private-query.md, docs/api/api-reference/edit-queries/update-query.md, docs/api/api-reference/execute-queries/cancel-execution.md, docs/api/api-reference/execute-queries/execute-query-id.md, docs/api/api-reference/get-results/execution-results.md, docs/api/api-reference/get-results/execution-status.md, docs/api/api-reference/get-results/latest-results.md, docs/api/api-reference/index.md, docs/api/index.md, mkdocs.insiders.yml
wanted to add a section top level with all endpoints
=> add rework

docs/data-tables/community/neynar/farcaster/fids.md, docs/data-tables/community/neynar/farcaster/fnames.md, docs/data-tables/community/neynar/farcaster/index.md, docs/data-tables/community/neynar/farcaster/links.md, docs/data-tables/community/neynar/farcaster/profiles_with_addresses.md, docs/data-tables/community/neynar/farcaster/reactions.md, docs/data-tables/community/neynar/farcaster/signers.md, docs/data-tables/community/neynar/farcaster/storage.md, docs/data-tables/community/neynar/farcaster/user_data.md, docs/data-tables/community/neynar/farcaster/verifications.md
- Fixes table names across 9 other markdown files
- Add profiles_with_addresses to index
=> fix: correct the table names across each of them

docs/query/DuneSQL-reference/Functions-and-operators/index.md, docs/query/DuneSQL-reference/Functions-and-operators/varchar-utility-functions.md
Towards NGN-119
`initcap` will be included on DuneSQL this week (https://github.com/duneanalytics/arrakis-jobs/pull/3000)
=> Document DuneSQL varchar functions

docs/api/api-reference/upload-data/index.md, docs/app/upload-data.md
adding delete data functionality docs
=> add delete data sections

overrides/main.html
Guides:
- AwesomeQA integration guide: https://awesome-qa.notion.site/Web-chatbot-integration-developer-manual-ba3616aabeb14e818b5117439822b013
- Overriding blocks on Mkdocs: https://squidfunk.github.io/mkdocs-material/customization/?h=script#overriding-blocks
- Playground: https://awesomeqa.xyz/chat-widget-test?communityId=eba081b4-d576-4e16-80a4-3ab3936be38a
=> Add Support Widget

.gitignore, overrides/main.html
=> Add in amplitude script

docs/index.md, docs/learning/index.md
Restructuring and revamping the learning resources parent page for better accessibility and readability.
=> Farcaster network analysis

docs/data-tables/index.md
Add:
Zksync
Zora
Celo
to documentation index page
=> Add missing chains to documentation

docs/app/decoding-contracts.md
ran into a 404 when trying to find the link for submitted contracts
=> update link for submitted contracts

docs/query/DuneSQL-reference/Functions-and-operators/conversion.md
Reverts duneanalytics/docs#422
=> Revert "Document implicit coercions in DuneSQL"

docs/query/DuneSQL-reference/Functions-and-operators/conversion.md
Updated documentation including support for decimal types with scale > 0.
=> Document implicit coercions in DuneSQL

docs/query/DuneSQL-reference/Functions-and-operators/chain-utility-functions.md
Towards NGN-1274
Towards NGN-1273
=> Add all_op_chains and get_balancer_link functions

docs/query/query-a-query.md
=> Document querying queries parameter limitations

docs/app/decoding-contracts.md
Reverts duneanalytics/docs#455
=> Revert "Update decoding-contracts.md"
